name: pfp_env
channels:
  - conda-forge
dependencies:
  - python=2.7
  - cftime
  - configobj
  - python-dateutil
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pyqt
  - pytz
  - scipy
  - statsmodels
  - timezonefinder=3.4.0
  - xlwt
  - xlrd
  - xlsxwriter
