name: pfp_gui
channels:
  - conda-forge
dependencies:
  - python=2.7
  - configobj
  - dateutil
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pyqt=4
  - pytz
  - scipy
  - statsmodels
  - timezonefinder=3.4.0
  - xlwt
  - xlrd
  - xlsxwriter
