name: pfp_gui
channels:
  - conda-forge
dependencies:
  - python=2.7
  - configobj
  - dateutil
  - matplotlib
  - netcdf4
  - numpy
  - pandas=0.21
  - pyqt=4
  - pytz
  - scipy
  - statsmodels
  - timezonefinder=3.3.0
  - xlwt
  - xlrd
  - xlsxwriter
