name: pfp_gui
dependencies:
  - python=2.7
  - configobj
  - dateutil
  - jupyter
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pyqt=4
  - pytz
  - scipy
  - statsmodels
  - xlwt
  - xlrd
  - xlsxwriter

